// let somenum = 33;
// let stringNumber = String(somenum);
// console.log(stringNumber);
// console.log(typeof stringNumber);
// let value = 3;
// let negValue = -value;
// console.log(negvalue);
const id = Symbol('123');
const another = Symbol('123');
console.log(id===another);
